title: KurzGeschichten
author: KurzGeschichten
description: Kurzgeschichten - Geschichten fürs Herz
url: https://ehmetkara21-dotcom.github.io/kurzgeschichten
plugins:
  - jekyll-paginate
exclude:
  - README.md
  - .gitignore
